/**
 * PWA Assets Builder Configuration
 * The configuration that will be used in order to generate the PWA Assets.
 */
const CONFIG = Object.freeze({
  // the exact width and height the logo image needs to be in order for the assets to be generated
  logoDimensionsRequirement: { width: 1024, height: 1024 },

  // the list of assets that will be generated by category.
  // The logo scale is a float and can range from 0 - 1
  output: {
    icons: [
      { dimensions: { width: 16, height: 16 }, logoScale: 0.012 },
      { dimensions: { width: 20, height: 20 }, logoScale: 0.014 },
      { dimensions: { width: 24, height: 24 }, logoScale: 0.016 },
      { dimensions: { width: 30, height: 30 }, logoScale: 0.022 },
      { dimensions: { width: 32, height: 32 }, logoScale: 0.024 },
      { dimensions: { width: 36, height: 36 }, logoScale: 0.027 },
      { dimensions: { width: 40, height: 40 }, logoScale: 0.030 },
      { dimensions: { width: 44, height: 44 }, logoScale: 0.033 },
      { dimensions: { width: 48, height: 48 }, logoScale: 0.037 },
      { dimensions: { width: 50, height: 50 }, logoScale: 0.038 },
      { dimensions: { width: 55, height: 55 }, logoScale: 0.042 },
      { dimensions: { width: 60, height: 60 }, logoScale: 0.044 },
      { dimensions: { width: 63, height: 63 }, logoScale: 0.046 },
      { dimensions: { width: 64, height: 64 }, logoScale: 0.046 },
      { dimensions: { width: 66, height: 66 }, logoScale: 0.046 },
      { dimensions: { width: 71, height: 71 }, logoScale: 0.047 },
      { dimensions: { width: 72, height: 72 }, logoScale: 0.047 },
      { dimensions: { width: 75, height: 75 }, logoScale: 0.048 },
      { dimensions: { width: 80, height: 80 }, logoScale: 0.05 },
      { dimensions: { width: 88, height: 88 }, logoScale: 0.054 },
      { dimensions: { width: 89, height: 89 }, logoScale: 0.055 },
      { dimensions: { width: 96, height: 96 }, logoScale: 0.06 },
      { dimensions: { width: 100, height: 100 }, logoScale: 0.063 },
      { dimensions: { width: 107, height: 107 }, logoScale: 0.066 },
      { dimensions: { width: 120, height: 120 }, logoScale: 0.072 },
      { dimensions: { width: 128, height: 128 }, logoScale: 0.076 },
      { dimensions: { width: 142, height: 142 }, logoScale: 0.085 },
      { dimensions: { width: 144, height: 144 }, logoScale: 0.087 },
      { dimensions: { width: 150, height: 150 }, logoScale: 0.090 },
      { dimensions: { width: 152, height: 152 }, logoScale: 0.092 },
      { dimensions: { width: 168, height: 168 }, logoScale: 0.105 },
      { dimensions: { width: 176, height: 176 }, logoScale: 0.109 },
      { dimensions: { width: 180, height: 180 }, logoScale: 0.112 },
      { dimensions: { width: 188, height: 188 }, logoScale: 0.118 },
      { dimensions: { width: 192, height: 192 }, logoScale: 0.12 },
      { dimensions: { width: 200, height: 200 }, logoScale: 0.131 },
      { dimensions: { width: 225, height: 225 }, logoScale: 0.142 },
      { dimensions: { width: 256, height: 256 }, logoScale: 0.165 },
      { dimensions: { width: 284, height: 284 }, logoScale: 0.187 },
      { dimensions: { width: 300, height: 300 }, logoScale: 0.20 },
      { dimensions: { width: 310, height: 150 }, logoScale: 0.102 },
      { dimensions: { width: 310, height: 310 }, logoScale: 0.208 },
      { dimensions: { width: 384, height: 384 }, logoScale: 0.24 },
      { dimensions: { width: 388, height: 188 }, logoScale: 0.122 },
      { dimensions: { width: 388, height: 388 }, logoScale: 0.26 },
      { dimensions: { width: 465, height: 225 }, logoScale: 0.145 },
      { dimensions: { width: 465, height: 465 }, logoScale: 0.29 },
      { dimensions: { width: 512, height: 512 }, logoScale: 0.32 },
      { dimensions: { width: 600, height: 600 }, logoScale: 0.370 },
      { dimensions: { width: 620, height: 300 }, logoScale: 0.20 },
      { dimensions: { width: 620, height: 620 }, logoScale: 0.38 },
      { dimensions: { width: 775, height: 375 }, logoScale: 0.26 },
      { dimensions: { width: 930, height: 450 }, logoScale: 0.31 },
      { dimensions: { width: 1024, height: 1024 }, logoScale: 0.65 },
      { dimensions: { width: 1240, height: 600 }, logoScale: 0.40 },
      { dimensions: { width: 1240, height: 1240 }, logoScale: 0.80 },
      { dimensions: { width: 2480, height: 1200 }, logoScale: 0.83 },
    ],
    'apple-touch-icons': [
      { dimensions: { width: 16, height: 16 }, logoScale: 0.012 },
      { dimensions: { width: 20, height: 20 }, logoScale: 0.014 },
      { dimensions: { width: 29, height: 29 }, logoScale: 0.022 },
      { dimensions: { width: 32, height: 32 }, logoScale: 0.024 },
      { dimensions: { width: 40, height: 40 }, logoScale: 0.030 },
      { dimensions: { width: 50, height: 50 }, logoScale: 0.037 },
      { dimensions: { width: 57, height: 57 }, logoScale: 0.043 },
      { dimensions: { width: 58, height: 58 }, logoScale: 0.043 },
      { dimensions: { width: 60, height: 60 }, logoScale: 0.043 },
      { dimensions: { width: 64, height: 64 }, logoScale: 0.043 },
      { dimensions: { width: 72, height: 72 }, logoScale: 0.047 },
      { dimensions: { width: 76, height: 76 }, logoScale: 0.049 },
      { dimensions: { width: 80, height: 80 }, logoScale: 0.051 },
      { dimensions: { width: 87, height: 87 }, logoScale: 0.053 },
      { dimensions: { width: 100, height: 100 }, logoScale: 0.06 },
      { dimensions: { width: 114, height: 114 }, logoScale: 0.07 },
      { dimensions: { width: 120, height: 120 }, logoScale: 0.072 },
      { dimensions: { width: 128, height: 128 }, logoScale: 0.076 },
      { dimensions: { width: 144, height: 144 }, logoScale: 0.087 },
      { dimensions: { width: 152, height: 152 }, logoScale: 0.092 },
      { dimensions: { width: 167, height: 167 }, logoScale: 0.105 },
      { dimensions: { width: 180, height: 180 }, logoScale: 0.112 },
      { dimensions: { width: 192, height: 192 }, logoScale: 0.12 },
      { dimensions: { width: 256, height: 256 }, logoScale: 0.165 },
      { dimensions: { width: 512, height: 512 }, logoScale: 0.32 },
      { dimensions: { width: 1024, height: 1024 }, logoScale: 0.65 },
    ],
    'apple-splash-screens': [
      { dimensions: { width: 640, height: 1136 }, logoScale: 0.175 },
      { dimensions: { width: 750, height: 1334 }, logoScale: 0.195 },
      { dimensions: { width: 828, height: 1792 }, logoScale: 0.265 },
      { dimensions: { width: 1125, height: 2436 }, logoScale: 0.341 },
      { dimensions: { width: 1136, height: 640 }, logoScale: 0.175 },
      { dimensions: { width: 1242, height: 2208 }, logoScale: 0.347 },
      { dimensions: { width: 1242, height: 2688 }, logoScale: 0.375 },
      { dimensions: { width: 1334, height: 750 }, logoScale: 0.195 },
      { dimensions: { width: 1536, height: 2048 }, logoScale: 0.335 },
      { dimensions: { width: 1668, height: 2224 }, logoScale: 0.377 },
      { dimensions: { width: 1668, height: 2388 }, logoScale: 0.385 },
      { dimensions: { width: 1792, height: 828 }, logoScale: 0.215 },
      { dimensions: { width: 2048, height: 1536 }, logoScale: 0.321 },
      { dimensions: { width: 2048, height: 2732 }, logoScale: 0.417 },
      { dimensions: { width: 2208, height: 1242 }, logoScale: 0.300 },
      { dimensions: { width: 2224, height: 1668 }, logoScale: 0.345 },
      { dimensions: { width: 2388, height: 1668 }, logoScale: 0.367 },
      { dimensions: { width: 2436, height: 1125 }, logoScale: 0.295 },
      { dimensions: { width: 2688, height: 1242 }, logoScale: 0.328 },
      { dimensions: { width: 2732, height: 2048 }, logoScale: 0.415 },
    ],
    telegram: [
      { dimensions: { width: 512, height: 512 }, logoScale: 0.32 },
    ],
    facebook: [
      { dimensions: { width: 720, height: 720 }, logoScale: 0.42 },
    ],
    github: [
      { dimensions: { width: 500, height: 500 }, logoScale: 0.32 },
    ],
    instagram: [
      { dimensions: { width: 1000, height: 1000 }, logoScale: 0.65 },
    ],
    linkedin: [
      { dimensions: { width: 400, height: 400 }, logoScale: 0.24 },
    ],
    notification: [
      { dimensions: { width: 256, height: 256 }, logoScale: 0.18 },
    ],
    tiktok: [
      { dimensions: { width: 200, height: 200 }, logoScale: 0.12 },
    ],
    twitter: [
      { dimensions: { width: 400, height: 400 }, logoScale: 0.24 },
    ],
    whatsapp: [
      { dimensions: { width: 500, height: 500 }, logoScale: 0.32 },
    ],
  },
});



/* ************************************************************************************************
 *                                         MODULE EXPORTS                                         *
 ************************************************************************************************ */
export {
  CONFIG,
};
